Module2 task3
htmlacademy-nodejs/280939-buy-and-sell-3 pull request #5
Opened 2020-05-15 22:38 UTC by topus009

2020-05-20 09:37 UTC, pan-alexey requested changes

2020-05-20 09:37 UTC, pan-alexey commented on package.json
> +    "server": "npm start -- --server",
--

2020-05-25 16:12 UTC, advokatevok requested changes

2020-05-25 16:12 UTC, thuwie commented on package.json
> +    "server": "cross-env COMMAND=\"--server\" npm start",
Если используется дополнительная зависимость cross-env, то она должна быть в dev-dependencies, чтобы при установке на новой машине у проекта было все, что нужно для запуска.

2020-05-25 18:26 UTC, merged